version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - ./metabase-db:/metabase.db
    - ./sqlite3.db:/sqlite3.db
    ports:
      - 3000:3000
