name: release
on: [push]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: REACT_APP_IPFS_BUILD=true yarn build
